### ISSUE TITLE
Supporting WebAPI

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/CommonEvidenceModel#13]
Here would be a good place to start:
http://www.ohdsi.org/web/wiki/doku.php?id=documentation:software:splicer

Tagging @anthonysena

**Comment by ericaVoss** [comment]
@anthonysena discussed that the majority of the calls are ported over.  With exception of the roll-up call, we have decided that we don't need to recreate it as there is no longer a use case.

@anthonysena to mark all calls not used as "deprecated" calls.
http://www.ohdsi.org/web/wiki/doku.php?id=documentation:software:splicer

@anthonysena to take first stab at documentation on Wiki and Erica to fill in.

**Comment by ericaVoss** [comment]
@anthonysena to share code with Erica to review documentation about Web API calls.

@rkboyce would like to register calls with BioCaddie, DataMed
https://datamed.org/

**Comment by rkboyce** [comment]
Also - did we fix the site navigation label to say 'Common Evidence Model' : (see left side: http://www.ohdsi.org/web/wiki/doku.php?id=documentation:software:splicer)

**Comment by anthonysena** [comment]
@ericaVoss - the documentation for the WebAPI calls can be found in the Java class:

https://github.com/OHDSI/WebAPI/blob/1731170ca61dc55e2e4b099b810ce8530516e638/src/main/java/org/ohdsi/webapi/service/EvidenceService.java

If you scroll down to one of the methods:

https://github.com/OHDSI/WebAPI/blob/1731170ca61dc55e2e4b099b810ce8530516e638/src/main/java/org/ohdsi/webapi/service/EvidenceService.java#L169

You will see the comments that are then used to create the documentation. We can make any adjustments to it since it is still under review.

**Comment by ericaVoss** [comment]
Because I do not have permissions to check in, here is the updated file.  I provided nothing of substance so you can take it or leave it.

[EvidenceService.zip](https://github.com/OHDSI/CommonEvidenceModel/files/1861855/EvidenceService.zip)

**Comment by ericaVoss** [comment]
- [ ] Get updated interface into beta
- [ ] Test beta interface 
- [ ] Prepare documentation in CEM Wiki
- [ ] Deploy to ATLAS by 5/1
